---
path:
  output: assets
  css: css
  js: js

# cdn setting
asset_host:
  # - http://assets1.example.com
  # - http://assets2.example.com

css:
  # css group name
  common:
    site:
      - bootstrap
      - desert
    cdn:
      - http://fonts.googleapis.com/css?family=Merriweather:400,300,700,900
  topics:
    site:
      - posts
  new-edit-topic:
    site:
      - new-edit
  users:
    site:
      - users
  user:
    site:
      - user
  article:
    site:
      - article
  tags:
    site:
      - tags
  notifications:
    site:
      - notifications

js:
  # js group name
  common:
    cdn:
      # - https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js
    site:
      - common/prettify
      - common/jquery-1.7.1.min
      - common/bootstrap
      - common/forum
