# development
server:
  # optional, default: 127.0.0.1
  host:
  # optional, default: 4000
  port:
  timezone: UTC
  cluster:  false
  base_url: http://127.0.0.1:4000/

db:
  db: forum-coke-dev
  # optional, default: localhost
  host:
  # optional, default: 27017
  port:
  # optional
  username:
  # optional
  password:

session:
  # optional, default: sessions
  collection:
  secret: 2e798a6d81f7235c10a93313dc222b5763a62ba6

passport:
  google_client_id: 169561998917.apps.googleusercontent.com
  google_client_secret: gEIf8pag_DBCoouzB75nr66G
  callback_url: http://localhost:4000/auth/callback

logs:
  - sys
  - request
  - response
  - error
  - debug

libs:
  - background

# libs that must run after server started
started:

aws:
  # your aws key & secret, those must not be empty if you set s3 option to true in assets config
  key:
  secret:
  s3:
    bucket: assets.dev.forum-coke

